// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.

// Example 2:

// Input: s = "", t = "y"
// Output: "y"


// Constraints:

// 0 <= s.length <= 1000
// t.length == s.length + 1
// s and t consist of lowercase English letters.

function findTheDifference(s, t) {
    let sSum = 0;
    let tSum = 0;
    for (let i = 0; i < s.length; i++) {
        sSum += s.charCodeAt(i);
    }
    for (let i = 0; i < t.length; i++) {
        tSum += t.charCodeAt(i);
    }
    return String.fromCharCode(tSum - sSum);
}

// Time Complexity: O(n)
// Space Complexity: O(1)

// Example Usage:
console.log(findTheDifference("abcd", "abcde")); // "e"
console.log(findTheDifference("", "y")); // "y"
